### ISSUE TITLE
There are no releases, what branch should be used in current FF?

### ISSUE THREAD

**Issue by joakim-tjernlund** [mozilla/gmp-api#18]

**Comment by SingingTree** [comment]
https://searchfox.org/mozilla-central/source/dom/media/gmp/gmp-api is the directory where Firefox currently stores the API files. You could use the ones from there (they can also be pulled from the Mozilla central repository).

Many of the folks who were previously updating this repo have moved on from Mozilla, so it's a bit out of date. I'll see if I can get the current version of the API pushed to here.

**Comment by joakim-tjernlund** [comment]
Mozilla central seems to HG and is very big so pulling from there feels awkward.

Would be great if you could push your API here again, thanks

**Comment by SingingTree** [comment]
https://github.com/mozilla/gmp-api/pull/19 should be the current version of the API in mozilla central. I had a quick look, and it seems to be largely style changes. It's possible it's all style except for the new `gmp-sanitized-cdm-exports.h` file, but I suggest ignoring that as I think it should be removed from the API.
